# Generated by Django 3.1.1 on 2021-01-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('body', models.TextField(max_length=10000, verbose_name='Статья (Новость)')),
                ('datetime_create', models.DateTimeField(auto_now=True)),
                ('datetime_to_start_show', models.DateTimeField()),
                ('datetime_to_last_update', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mylocaluser')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='SectionNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Раздел сайта')),
                ('datetime_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Раздел  новостей',
                'verbose_name_plural': 'Разделы новостей',
                'db_table': 'sectionnews',
            },
        ),
        migrations.CreateModel(
            name='NewsCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name': 'Счетчик новостей',
                'verbose_name_plural': 'Счетчик новостей',
                'db_table': 'newscounter',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.sectionnews'),
        ),
    ]
