# Generated by Django 3.1.1 on 2021-01-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_commentnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
