# Generated by Django 3.1.1 on 2021-02-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='test_descript', max_length=300, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
