# Generated by Django 3.1.1 on 2021-02-02 08:14

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210201_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tiny_image',
            field=models.ImageField(default='qwe', upload_to=news.models.get_path_to_tiny_image, verbose_name='Маленькая картинка'),
            preserve_default=False,
        ),
    ]
