# Generated by Django 3.1.1 on 2021-01-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210130_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
