# Generated by Django 3.1.1 on 2021-01-30 19:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podrazdelenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название подразделения')),
                ('unicum_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'podrazdelenie',
            },
        ),
        migrations.CreateModel(
            name='MyLocalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('index_sortirovki', models.IntegerField(blank=True, null=True, verbose_name='Индекс сортировки')),
                ('position', models.CharField(max_length=150, verbose_name='Должность в организации')),
                ('podrazdelenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.podrazdelenie')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'mylocaluser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
