# Generated by Django 3.1.1 on 2021-01-30 19:43

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('datetime_create', models.DateTimeField(auto_now=True)),
                ('datetime_to_start_show', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала показа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mylocaluser')),
            ],
            options={
                'verbose_name': 'Папка для видео',
                'verbose_name_plural': 'Папки для видео',
                'db_table': 'videofolder',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('datetime_create', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to=video.models.path_to_upload_video)),
                ('datetime_to_start_show', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала показа')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videofolder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mylocaluser')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Все видео',
                'db_table': 'video',
            },
        ),
    ]
